[![imag/pythonista.png](img/pythonista.png)](https://www.pythonista.io)

# Transformación de *dataframes* y series.

En la mayoría de los casos los conjuntos de datos (*datasets*) a los que se accede con *Pandas* incluyen información que debe de ser ajustada o extraída.

En este capítulo se explorarán algunas herramientas que permiten transformar a los *dataframes* y series de *Pandas* a fin de extraer y mostrar información de diversos modos.

In [1]:
import pandas as pd
import numpy as np

## *Dataframe* ilustrativo.

El *dataframe* ```poblacion``` contiene datos ficticios de un muestreo poblacional de animales en diversas regiones geográficas.

In [2]:
poblacion = pd.DataFrame({'Animal':('lobo',
                                    'coyote',
                                   'jaguar',
                                   'cerdo salvaje',
                                    'tapir',
                                    'venado',
                                    'ocelote',
                                    'puma'),
                         'Norte_I':(12,
                                   np.nan,
                                    None,
                                    2,
                                    4,
                                    2,
                                    14,
                                    5
                                   ),
                          'Norte_II':(23,
                                    4,
                                    25,
                                    21,
                                    9,
                                    121,
                                    1,
                                    2
                                   ),
                         'Centro_I':(15,
                                    23,
                                    2,
                                    120,
                                    40,
                                    121,
                                    0,
                                    5),
                         'Sur_I':(28,
                                  46,
                                  14,
                                  156,
                                  79,
                                  12,
                                  2,
                                  np.nan)}).set_index('Animal')

In [3]:
poblacion

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo              12.0        23        15   28.0
coyote             NaN         4        23   46.0
jaguar             NaN        25         2   14.0
cerdo salvaje      2.0        21       120  156.0
tapir              4.0         9        40   79.0
venado             2.0       121       121   12.0
ocelote           14.0         1         0    2.0
puma               5.0         2         5    NaN

## El método ```df.combine()```.

El método ```combine()``` permite comparar dos *dataframes* por columnasy aplicar una función a cada par de elementos correspondientes para obtener un nuevo *dataframe*. 

```
df.combine(<dataframe>, <func>, axis=0, fill_value=<valor>)
```

Donde:
* ```<dataframe>``` es un *dataframe* cuyos índices y columnas coinciden con los índices y columnas del *dataframe* que contiene al método ```combine()```.
* ```<func>``` es una función que comparará cada par de elementos correspondientes de los dos *dataframes* y devolverá un nuevo valor.
* ```<valor>``` es un valor que se utilizará para reemplazar los valores faltantes antes de aplicar la función.

El primer argumento de la función ```<func>``` es el elemento del *dataframe* que contiene al método ```combine()```, mientras que el segundo argumento es el elemento del *dataframe* pasado como primer argumento del método.


https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine.html

**Ejemplos:**

* La siguiente celda define al *dataframe* `otra_poblacion`.

In [4]:
otra_poblacion = pd.DataFrame({
        'Animal':(
            'lobo',
            'coyote',
            'jaguar',
            'cerdo salvaje',),
        'Norte_I':(
            1,
            1,
            1,
            1,),
        'Centro_II':(
            1,
            1, 
            1,
            1,)

        }).set_index('Animal')

In [9]:
otra_poblacion

               Norte_I  Centro_II
Animal
lobo                 1          1
coyote               1          1
jaguar               1          1
cerdo salvaje        1          1

* Se utilizará el *dataframe* ```poblacion``` definido previamente.

In [5]:
poblacion

               Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo              12.0        23        15   28.0
coyote             NaN         4        23   46.0
jaguar             NaN        25         2   14.0
cerdo salvaje      2.0        21       120  156.0
tapir              4.0         9        40   79.0
venado             2.0       121       121   12.0
ocelote           14.0         1         0    2.0
puma               5.0         2         5    NaN

* La funcion `promedio()` es definida a continuación.
   * La función recibe dos series como argumentos.
   * En caso de que una de las series contenga únicamente valores `np.nan` (lo que ocurre generalmente cuando el elementro corresondiente no existe en uno de los *dataframes*), la función devolverá la otra serie.
   * En cualquier otro caso, regresará una serie con el resultado de calcular el promedio de cada par de elementos correspondientes de ambas series.

In [7]:
def promedio( derecha:pd.Series, izquierda:pd.Series) -> pd.Series:
    if derecha.isna().all():
        return izquierda
    if izquierda.isna().all():
        return derecha
    return (derecha + izquierda) / 2

* La siguiente celda regresará un *dataframe* resultante de combinar los *dataframes* `poblacion` y `otra_poblacion` utilizando la función `promedio()`.
* En este caso, una operación aritmética en la que uno de los operandos es `np.nan` devolverá `np.nan`.

In [8]:
poblacion.combine(otra_poblacion, promedio)

               Centro_I  Centro_II  Norte_I  Norte_II  Sur_I
Animal
cerdo salvaje     120.0        1.0      1.5      21.0  156.0
coyote             23.0        1.0      NaN       4.0   46.0
jaguar              2.0        1.0      NaN      25.0   14.0
lobo               15.0        1.0      6.5      23.0   28.0
ocelote             0.0        NaN      NaN       1.0    2.0
puma                5.0        NaN      NaN       2.0    NaN
tapir              40.0        NaN      NaN       9.0   79.0
venado            121.0        NaN      NaN     121.0   12.0

* La siguiente celda regresará un *dataframe* resultante de combinar los *dataframes* `poblacion` y `otra_poblacion` utilizando la función `promedio()`.
* Los valores faltantes se reemplazarán por `0` antes de aplicar la función `promedio()`.

In [10]:
poblacion.combine(otra_poblacion, promedio, fill_value=0)

               Centro_I  Centro_II  Norte_I  Norte_II  Sur_I
Animal
cerdo salvaje      60.0        0.5      1.5      10.5   78.0
coyote             11.5        0.5      0.5       2.0   23.0
jaguar              1.0        0.5      0.5      12.5    7.0
lobo                7.5        0.5      6.5      11.5   14.0
ocelote             0.0        0.0      7.0       0.5    1.0
puma                2.5        0.0      2.5       1.0    0.0
tapir              20.0        0.0      2.0       4.5   39.5
venado             60.5        0.0      1.0      60.5    6.0

## El método ```df.transpose()```.

El método ```df.transpose()``` permite cambiar los ejes de un dataframe y regresará un nuevo dataframe en el que los índices de los renglones serán los de las columnas y viceversa.

```
df.transpose()
```

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transpose.html

**Ejemplo:**

* La siguiente celda creará un dataframe con nombre ```poblacion_traspuesta``` el cual es el resultado de ejecutar el método ```transpose()``` del dataframe ```poblacion```.

In [ ]:
poblacion_traspuesta = poblacion.transpose()

In [ ]:
poblacion_traspuesta

## El método ```melt()```.

Al analizar un dataset, es común identificar elementos de este que infuyen en el resultado de otro.

El método ```melt()``` permite extraer datos a partir de un *dataframe*, identificando causas (```id_vars ```) y efectos (```value_vars```), permitiendo hacer más explícita esta relación.

Este método crea un nuevo *dataframe* en el que las columnas enumeradas como ```value_vars``` se presentan en función de las columnas enumeradas como ```id_vars```.

```
df.melt(id_vars=[<col i1>, <col i2>, ... <col in>], 
 value_vars=[<col v1>, <col v2>, ... <columnas vn>,
 var_name='<nombre de variable>',
 value_name='<nombre de valores>'])
```

Donde:

* ```<col ix>``` son las columnas que se designan como variables independientes.
* ```<col vx>``` son las columnas que se designan como variables dependientes de las columnas definidas en ```id_vars```.
* ```<nombre de variable>``` es el nombre que se le puede dar a la columna ```'variable'```.
* ```<nombre de valores>``` es el nombre que se le puede dar a la columna ```'value'```.

El *dataframe* resultante presentará:

* Las columnas listadas en el parámetro ```id_vars```. 
* Una columna llamada por defecto ```variable``` que contendrá en sus renglones los nombres de las columnas listadas en el parámetro ```value_vars```. El nombre de esta columna puede asignarse mediante el parámetro ``` var_name```.
* Una columna llamada por defecto ```value``` que contendrá los valores contenidos a su vez en las columnas listadas en el parámetro ```value_vars```. El nombre de esta columna puede asignarse mediante el parámetro ``` value_name```.

El *dataframe* mostrará las diversas combinaciones posibles entre las variables independientes que están relacionadas a las variables dependientes y los índices serán numéricos.

https://pandas.pydata.org/docs/reference/api/pandas.melt.html

**Ejemplos:**

* Se utilizará el *dataframe* ```poblacion_traspuesta``` definido previamente.

In [ ]:
poblacion_traspuesta

* La siguiente celda regresará un dataframe creado a partir de ```poblacion_traspuesta``` en el que la columna ```'lobo'``` se enlista en el parámetro ```id_vars``` y la columna ```venado``` se enlista en el parámetro ```value_vars```.

In [ ]:
poblacion_traspuesta.melt(id_vars=["lobo"], value_vars=["venado"])

* La siguiente celda regresará un dataframe creado a partir de ```poblacion_traspuesta``` en el que:
 * ```id_vars=["lobo", "coyote"]```
 * ```value_vars=["venado"]```.

In [ ]:
poblacion_traspuesta.melt(id_vars=["lobo", "coyote"], value_vars=["venado"])

* La siguiente celda regresará un dataframe creado a partir de ```poblacion_traspuesta``` en el que:
 * ```id_vars=["lobo", "coyote"]```
 * ```value_vars=["venado, "cerdo salvaje"]```.
 * ```var_name="presa"```, 
 * ```value_name="población"```

In [ ]:
poblacion_traspuesta.melt(id_vars=["lobo", "coyote"], value_vars=["venado", "cerdo salvaje"], 
                 var_name="presa", value_name="población")

## El método ```stack()```.

Este método transforma a un *dataframe* en una serie.

```
df.stack()
```

Las serie resultante cuenta con un índice jerárquico, también conocido como *MultiIndex*.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html

In [ ]:
poblacion

* La siguiente celda aplciará el método ```stack()``` al *dataframe* ```poblacion``` y se le asignará el nombre ```poblacion_apilada``` a la serie resultante.

In [ ]:
poblacion_apilada = poblacion.stack()

In [ ]:
poblacion_apilada

* La siguiente celda muestra el atributo ```index``` de la serie ```poblacion_apilada```.

In [ ]:
poblacion_apilada.index

* La siguiente celda regresará los elementos del índice `'lobo'` de la serie `poblacion_apilada`.

In [ ]:
poblacion_apilada['lobo']

* La siguente celda regresará el elemento con índice '`lobo`' y '`Norte-I`' de la serie `poblacion_apilada`.

In [ ]:
poblacion_apilada['lobo']['Norte_I']

## El método ```serie.unstack()```.

El método ```unstack()``` permite convertir una serie creada con el método ```stack()``` en un dataframe.

```serie.unstack()
```
 https://pandas.pydata.org/docs/reference/api/pandas.Series.unstack.html

**Ejemplo:**

* La siguiente celda aplicará el método `unstack()` a la serie `poblacion_apilada`.

In [ ]:
poblacion_apilada.unstack()

## El método ```df.pivot()```.
El método ```df.pivot()``` permite crear estructuras de *dataframes* a partir de columnas de un *dataframe* base.

Las columnas del *dataframe* original se utilizarán para definir los índices, columnas y valores del nuevo *dataframe*.

```
df.pivot(columns=<id_col>, index=<id_index>, values=<id_val>)
```
Donde:

* ```<id_col>``` es las columna del *dataframe* que corresponde a las columnas del nuevo *dataframe*.
* ```<id_index>``` es las columna del *dataframe* que corresponde a los índices del nuevo *dataframe*.
* ```<id_val>``` es las columna del *dataframe* que corresponde a los valores del nuevo *dataframe*.

**NOTA:** Los valores que se utilizarán para crear un nuevo *dataframe* deben de ser del mismo tamaño.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html

**Ejemplo:**

* La siguiente celda creará al *dataframe* `observaciones`, el cual representa:
   * El conteo de las variables: `'peatones'` y `'vehículos'`.
   * En diversas regiones geográficas: `'Norte'`, `'Sur'`, `'Este'`, `'Oeste'`.
   * A lo largo de distintos momentos del día: `'mañana'`, `'tarde'`, `'noche'`.

Este tipo de tablas se conocen como tablas de contingencia y son útiles para analizar la relación entre variables categóricas.

In [12]:
observaciones = pd.DataFrame({'region':('Norte', 'Norte', 'Norte',
                                        'Sur', 'Sur', 'Sur',
                                        'Este', 'Este', 'Este',
                                        'Oeste', 'Oeste', 'Oeste'),
                             'horario':('mañana', 'tarde', 'noche',
                                        'mañana', 'tarde', 'noche',
                                        'mañana', 'tarde', 'noche',
                                        'mañana', 'tarde', 'noche'),
                              'peatones':(153, 589, 35,
                                          215, 702, 87,
                                          95, 806, 22,
                                          290, 1390, 150),
                             'vehículos': (np.nan, 1003, 304,
                                          506, 1421, 150,
                                          271, 1863, 198,
                                          948, 2279, 804)})

In [13]:
observaciones

   region horario  peatones  vehículos
0   Norte  mañana       153        NaN
1   Norte   tarde       589     1003.0
2   Norte   noche        35      304.0
3     Sur  mañana       215      506.0
4     Sur   tarde       702     1421.0
5     Sur   noche        87      150.0
6    Este  mañana        95      271.0
7    Este   tarde       806     1863.0
8    Este   noche        22      198.0
9   Oeste  mañana       290      948.0
10  Oeste   tarde      1390     2279.0
11  Oeste   noche       150      804.0

* La siguiente celda regresará un nuevo *dataframe* creado a partir del *dataframe* `observaciones` utilizando el método `pivot()`. En este caso:
 * ```columns='region'```
 * ```index='horario'```
 * ```values='peatones'```

In [14]:
observaciones.pivot(columns='region', 
                    values='peatones', 
                    index='horario')

region   Este  Norte  Oeste  Sur
horario
mañana     95    153    290  215
noche      22     35    150   87
tarde     806    589   1390  702

* La siguiente celda regresará un nuevo *dataframe* creado a partir del *dataframe* `observaciones` utilizando el método `pivot()`. En este caso:
 * ```columns='region'```
 * ```index='horario'```
 * ```values='vehiculos'```

In [15]:
observaciones.pivot(columns='region', 
                    values='vehículos', 
                    index='horario')

region     Este   Norte   Oeste     Sur
horario
mañana    271.0     NaN   948.0   506.0
noche     198.0   304.0   804.0   150.0
tarde    1863.0  1003.0  2279.0  1421.0

## El método ```pd.pivot_table()```.

El método ```pivot_table()``` me permite crear tablas del mismo modo que ```pd.pivot()```, pero no es necesario que el tamaño de la nueva tabla sea igual al de la original. Aquellos valores faltantes que se utilicen para crear el nuevo *dataframe* pueden ser ponderados utilizando una función de agregación.

Las columnas del *dataframe* original se utilizarán para definir los índices, columnas y valores del nuevo *dataframe*.

```
df.pivot_table(columns=<id_col>, index=<id_index>, values=<id_val>, aggfunc=<func>)
```
Donde:

* ```<id_col>``` es las columna del *dataframe* que corresponde a las columnas del nuevo *dataframe*.
* ```<id_index>``` es las columna del *dataframe* que corresponde a los índices del nuevo *dataframe*.
* ```<id_val>``` es las columna del *dataframe* que corresponde a los valores del nuevo *dataframe*.
* ```<func>``` es la función de agregación que se aplicará a los valores ponderados del nuevo *dataframe*. La función por defecto es `np.mean()`.


https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot_table.html

**Ejemplo:**

La siguiente celda creará al *dataframe* `observaciones_2` el cual tiene la misma estructura que el *dataframe* `observaciones` pero con algunos valores faltantes con la excepción de que existe una observación adicional que hace que haya cuatro observaciones para la región `'Sur'` en el horario `'mañana'` mientras que el resto tiene tres observaciones.

In [19]:
observaciones_2 = pd.DataFrame({'region':('Norte', 'Norte', 'Norte',
                                        'Sur', 'Sur', 'Sur', 'Sur',
                                        'Este', 'Este', 'Este',
                                        'Oeste', 'Oeste', 'Oeste'),
                             'horario':('mañana', 'tarde', 'noche',
                                        'mañana', 'tarde', 'noche', 'mañana',
                                        'mañana', 'tarde', 'noche',
                                        'mañana', 'tarde', 'noche'),
                              'peatones':(153, 589, 35,
                                          215, 702, 87, 221,
                                          95, 806, 22,
                                          290, 1390, 150),
                             'vehiculos': (np.nan, 1003, 304,
                                          506, 1421, 150, np.nan,
                                          271, 1863, 198,
                                          948, 2279, 804)})

In [20]:
observaciones_2

   region horario  peatones  vehiculos
0   Norte  mañana       153        NaN
1   Norte   tarde       589     1003.0
2   Norte   noche        35      304.0
3     Sur  mañana       215      506.0
4     Sur   tarde       702     1421.0
5     Sur   noche        87      150.0
6     Sur  mañana       221        NaN
7    Este  mañana        95      271.0
8    Este   tarde       806     1863.0
9    Este   noche        22      198.0
10  Oeste  mañana       290      948.0
11  Oeste   tarde      1390     2279.0
12  Oeste   noche       150      804.0

* Debido a esta diferencia en el número de observaciones, el método `pivot()` no podrá crear un nuevo *dataframe* a partir del *dataframe* `observaciones_2` y se generará una excepción de tipo `ValueError`.
    * La columna `'region'` sería designada como las columnas del nuevo *dataframe*.
    * La columna `'horario'` sería designada como los índices del nuevo *dataframe*.
    * La columna `'vehiculos'` sería designada como los valores del nuevo *dataframe*.

In [24]:
observaciones_2.pivot(columns='region', 
                    values='vehiculos', 
                    index='horario')

ValueError: Index contains duplicate entries, cannot reshape

* El método `pivot_table()` sí podrá crear un nuevo *dataframe* a partir del *dataframe* `observaciones_2` y se generará una tabla de contingencia en la que el valor de cada celda será el promedio de los valores correspondientes a esa región y horario.
    * La columna `'region'` sería designada como las columnas del nuevo *dataframe*.
    * La columna `'horario'` sería designada como los índices del nuevo *dataframe*.
    * La columna `'vehiculos'` sería designada como los valores del nuevo *dataframe*.

In [22]:
observaciones_2.pivot_table(columns='region', 
                    values='vehiculos', 
                    index='horario')

region     Este   Norte   Oeste     Sur
horario
mañana    271.0     NaN   948.0   506.0
noche     198.0   304.0   804.0   150.0
tarde    1863.0  1003.0  2279.0  1421.0

*

In [23]:
observaciones_2.pivot_table(columns='region', 
                    values='peatones', 
                    index='horario')

region    Este  Norte   Oeste    Sur
horario
mañana    95.0  153.0   290.0  218.0
noche     22.0   35.0   150.0   87.0
tarde    806.0  589.0  1390.0  702.0

* La siguiente celda regresará un nuevo *dataframe* creado a partir del *dataframe* `observaciones_2` utilizando el método `pivot_table()`. En este caso:
 * ```columns='region'```
 * ```index='horario'```
 * ```values='vehiculos'```
 * ```aggfunc=np.sum()```

In [25]:
observaciones_2.pivot_table(columns='region', 
                    values='peatones', 
                    index='horario',
                    aggfunc=np.sum)

/tmp/ipykernel_42451/2708872106.py:1: FutureWarning: The provided callable <function sum at 0x797c100e34c0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  observaciones_2.pivot_table(columns='region',

region   Este  Norte  Oeste  Sur
horario
mañana     95    153    290  436
noche      22     35    150   87
tarde     806    589   1390  702

* La siguiente celda regresará un nuevo *dataframe* creado a partir del *dataframe* `observaciones_2` utilizando el método `pivot_table()`. En este caso:
 * ```columns='region'```
 * ```values='peatones'```

In [26]:
observaciones_2.pivot_table(columns='region', 
                    values='peatones')

region          Este  Norte  Oeste     Sur
peatones  307.666667  259.0  610.0  306.25

## El método pd.crosses().

El método `crosses()` permite crear un nuevo *dataframe* a partir de la combinación de dos o más columnas de un *dataframe* base. Este método es útil para analizar la relación entre variables categóricas.

```
df.crosses(columns=[<col1>, <col2>, ... <coln>], values=<col_val>, aggfunc=<func>)
```
Donde:
* ```<colx>``` son las columnas del *dataframe* que se utilizarán para crear el nuevo *dataframe*.
* ```<col_val>``` es la columna del *dataframe* que corresponde a los valores del nuevo *dataframe*.
* ```<func>``` es la función de agregación que se aplicará a los valores ponderados del nuevo *dataframe*. La función por defecto es `np.mean()`.

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2017-2026.</p>